config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :pandemics
  resources :data_urls

  root 'pandemics#index'

  post 'generate_report', to: 'reports#create'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_url.rb
class DataUrl < ApplicationRecord
  has_many :pandemic_data_associations, dependent: :destroy
  has_many :pandemics, through: :pandemic_data_associations

  validates :source_name, presence: true, uniqueness: true
  validates :source_url, presence: true, uniqueness: true
  validates :data_type, presence: true
  validates :data_type, inclusion: { in: %w[json rss] }

  def to_hash
    {
      source_id: id,
      source_name: source_name,
      source_url: source_url,
      source_type: data_type
    }
  end
end

app/models/pandemic.rb
class Pandemic < ApplicationRecord
  has_many :pandemic_data_associations, dependent: :destroy
  has_many :data_urls, through: :pandemic_data_associations

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  def present_data_urls
    data_urls.each_with_object([]) { |data_url, acc| acc << data_url.to_hash }
  end
end

app/models/pandemic_data_association.rb
class PandemicDataAssociation < ApplicationRecord
  belongs_to :pandemic
  belongs_to :data_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def cache(key)
    if block_given?
      Rails.cache.fetch(key) { yield }
    end
  end
end

app/controllers/data_urls_controller.rb
class DataUrlsController < ApplicationController
  before_action :data_url, only: %i[show edit update destroy]

  def index
    @data_urls = cache('all-data_urls') { DataUrl.all.to_a }
  end

  def show; end

  def new
    @data_url = DataUrl.new
  end

  def edit; end

  def create
    @data_url = DataUrl.new(data_url_params)

    if @data_url.save
      redirect_to @data_url, notice: 'Data Url was successfully created.'
    else
      render :new
    end
  end

  def update
    if @data_url.update(data_url_params)
      redirect_to @data_url, notice: 'Data Url was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @data_url.destroy

    redirect_to data_urls_url, notice: 'Data Url was successfully destroyed.'
  end

  private

  def data_url
    @data_url = cache("data-url-#{params[:id]}") { DataUrl.find(params[:id]) }
  end

  def data_url_params
    params.require(:data_url).permit(:source_name, :source_url, :data_type, :description)
  end
end

app/controllers/pandemics_controller.rb
class PandemicsController < ApplicationController
  include ErrorHandlers::RedisErrors

  before_action :data_urls, only: :edit
  before_action :destroy_pandemics_cache, only: %i[create update destroy]

  def index
    @pandemics = Pandemics::Factory::Index.manufacture.get
  end

  def show;
    @pandemic = Pandemics::Factory::Show.manufacture(params[:id]).get
  end

  def new
    @pandemic = Pandemics::Factory::New.manufacture.get
  end

  def edit; end

  def create
    @pandemic = Pandemic.new(pandemic_params)

    if @pandemic.save
      redirect_to(@pandemic, notice: 'Pandemic was successfully created.')
    else
      render :new
    end
  end

  def update
    if @pandemic.update(pandemic_params)
      redirect_to(@pandemic, notice: 'Pandemic was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    @pandemic.destroy

    redirect_to(pandemics_url, notice: 'Pandemic was successfully destroyed.')
  end

  private

  def data_urls
    @data_urls = cache('all-data_urls') { DataUrl.all.to_a }
  end

  def destroy_pandemics_cache
    Rails.cache.delete("pandemic-#{params[:id]}")
    Rails.cache.delete('all-pandemics')
  end

  def pandemic_params
    params.require(:pandemic).permit(:name, :description, data_url_ids: [])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ErrorHandlers::RedisErrors

  def create
    pandemic = Pandemic.find(reports_params[:pandemic_id])
    CreateReportEventJob.perform_later(pandemic)

    redirect_to pandemic_url(pandemic)
    flash[:notice] = "Report for #{pandemic.name} is being generated and will be available shortly."
  end

  private

  def reports_params
    params.require(:report).permit(:pandemic_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_status(name)
    name == controller_name ? 'active' : nil
  end
end

app/helpers/data_urls_helper.rb
module DataUrlsHelper
end

app/helpers/pandemic_data_associations_helper.rb
module PandemicDataAssociationsHelper
end

app/helpers/pandemics_helper.rb
module PandemicsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/data_urls/_form.html.erb
<%= form_with(model: data_url, local: true) do |form| %>
  <% if data_url.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><%= pluralize(data_url.errors.count, "error") %> prohibited this data url from being saved:</h5>
      <ul>
        <% data_url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group ml-3 mr-3">
    <%= form.label :source_name, class: "font-weight-bold" %>
    <%= form.text_field :source_name, class: "form-control" %>
  </div>
  <div class="form-group ml-3 mr-3">
    <%= form.label :source_url, class: "font-weight-bold" %>
    <%= form.text_field :source_url, class: "form-control" %>
  </div>
  <div class="form-group ml-3 mr-3">
    <%= form.label :data_type, class: "font-weight-bold" %>
    <%= form.text_field :data_type, class: "form-control" %>
  </div>
  <div class="form-group ml-3 mr-3">
    <%= form.label :description, class: "font-weight-bold" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="btn-group ml-3" role="group" aria-label="Pandemic New">
    <%= form.submit class: "btn btn-primary", role: "button" %>
<% end %>

app/views/data_urls/edit.html.erb
<div class="row">
  <div class="col-sm">
    <div class="dropdown-divider"></div>

    <%= render 'form', data_url: @data_url %>
      <%= link_to 'Show', data_url_path(@data_url), class: "btn btn-primary" %>
      <%= link_to 'Index', data_urls_url, class: "btn btn-primary" %>
    </div>
  </div>
</div>
</div>

app/views/data_urls/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert""><%= notice %></div>
<% end %>

<p class="ml-3"><%= link_to "New Data url", new_data_url_url, class: "btn btn-primary", role: "button" %></p>
<div class="dropdown-divider"></div>
<div class="card-columns m-3">

<% @data_urls.each do |data_url| %>
  <% cache data_url do %>
    <div class="card bg-light">
      <div class="card-body">
        <h5 class="card-title"><%= link_to data_url.source_name, data_url_path(data_url) %></h5>
        <div class="dropdown-divider"></div>
        <p class="card-text"><%= data_url.source_url %></p>
        <p class="card-text"><%= data_url.data_type %></p>
        <p class="card-text"><%= data_url.description %></p>
        <div class="card-footer">
          <small class="text-muted">Added on: <%= data_url.created_at.to_date %></small>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/data_urls/new.html.erb
<div class="row">
  <div class="col-sm">
    <div class="dropdown-divider"></div>

    <%= render 'form', data_url: @data_url %>
      <%= link_to 'Index', data_urls_url, class: "btn btn-primary" %>
    </div>
  </div>
</div>
</div>

app/views/data_urls/show.html.erb
<div class="row">
  <div class="col-sm">
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert""><%= notice %></div>
    <% end %>

    <h3 class="pt-2 pl-3"><%= @data_url.source_name %></h3>
    <div class="dropdown-divider"></div>
    <p class="text-justify pl-3 pr-3"><%= @data_url.source_url %></p>
    <p class="text-justify pl-3 pr-3"><%= @data_url.data_type %></p>

    <% if @data_url.description.present? %>
      <p class="text-justify pl-3 pr-3"><%= @data_url.description %></p>
    <% end %>

    <div class="dropdown-divider"></div>
    <div class="btn-group ml-3" role="group" aria-label="Pandemic Controls">
      <%= link_to "Edit", edit_data_url_path(@data_url), class: "btn btn-primary" %>
      <%= link_to "Destroy", @data_url, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <%= link_to 'Index', data_urls_url, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidNineteenReports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
      <%= link_to 'PandemicReports', root_url, class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= menu_status("pandemics") %>">
            <%= link_to 'Pandemics', pandemics_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= menu_status("data_urls") %>">
            <%= link_to 'Data-Urls', data_urls_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid pl-0 pr-0 min-height">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pandemics/_form.html.erb
<%= form_with(model: pandemic, local: true) do |form| %>
  <% if pandemic.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><%= pluralize(pandemic.errors.count, "error") %> prohibited this pandemic from being saved:</h5>
      <ul>
        <% pandemic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group ml-3 mr-3">
    <%= form.label :name, class: "font-weight-bold" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group ml-3 mr-3">
    <%= form.label :description, class: "font-weight-bold" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="py-2 mx-3 mb-3 bg-light">
    <div class="row px-2">
      <%= form.collection_check_boxes :data_url_ids, @data_urls, :id, :source_name, checked: @pandemic.data_url_ids.map(&:to_param) do |c| %>
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5">
          <div class="form-check">
            <%= c.check_box %>
            <%= c.label class: "ml-1" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="btn-group ml-3" role="group" aria-label="Pandemic New">
    <%= form.submit class: "btn btn-primary", role: "button" %>
  <% end %>

app/views/pandemics/edit.html.erb
<div class="row">
  <div class="col-sm">
    <h3 class="pt-2 pl-3">Edit Pandemic</h3>
    <div class="dropdown-divider"></div>

    <%= render 'form', pandemic: @pandemic %>
      <%= link_to 'Show', @pandemic, class: "btn btn-primary" %>
      <%= link_to 'Index', pandemics_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
</div>

app/views/pandemics/index.html.erb
<% if flash[:notice] %>
<div class="alert alert-success" role="alert""><%= notice %></div>
<% end %>
<p class=" ml-3 mt-3"><%= link_to 'New Pandemic', new_pandemic_path, class: "btn btn-primary", role: "button" %></p>
  <div class="dropdown-divider"></div>
  <div class="card-columns m-3">
    <% @pandemics.each do |pandemic| %>
    <% cache pandemic do %>
    <div class="card bg-light">
      <div class="card-body">
        <h5 class="card-title"><%= link_to pandemic.name, pandemic_path(pandemic) %></h5>
        <div class="dropdown-divider"></div>
        <p class="card-text"><%= pandemic.description %></p>
        <div class="card-footer">
          <small class="text-muted">Added on: <%= pandemic.created_at.to_date %></small>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>

app/views/pandemics/new.html.erb
<div class="row">
  <div class="col-sm">
    <h3 class="pt-2 pl-3">New Pandemic</h3>
    <div class="dropdown-divider"></div>

    <%= render 'form', pandemic: @pandemic.pandemic %>
      <%= link_to 'Index', pandemics_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
</div>

app/views/pandemics/show.html.erb
<div class="row">
  <div class="col-sm">
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <h3 class=" pt-2 pl-3"><%= @pandemic.name %></h3>
    <div class="dropdown-divider"></div>
    <p class="text-justify pl-3 pr-3"><%= @pandemic.description %></p>
    <p class="ml-3">Data Urls:</p>
    <div class="card-columns m-3">
      <% @pandemic.data_urls.each do |data_url| %>
        <% cache data_url do %>
          <div class="card bg-light">
            <div class="card-body">
              <h5 class="card-title"><%= link_to data_url.source_name, data_url_path(data_url) %></h5>
              <div class="dropdown-divider"></div>
              <p class="card-text"><%= data_url.source_url %></p>
              <p class="card-text"><%= data_url.description %></p>
              <div class="card-footer">
                <small class="text-muted">Added on: <%= data_url.created_at.to_date %></small>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="btn-group ml-3" role="group" aria-label="Pandemic Controls">
      <% cache "show_report_button_#{@pandemic.id}" do %>
        <% if @pandemic.data_urls.any? %>
          <%= link_to 'Report', generate_report_url(report: { pandemic_id: @pandemic }), method: :post, class: "btn btn-primary" %>
        <% end %>
      <% end %>
      <%= link_to 'Edit', edit_pandemic_path(@pandemic), class: "btn btn-primary" %>
      <%= link_to 'Destroy', @pandemic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <%= link_to 'Index', pandemics_path, class: "btn btn-primary" %>
    </div>
  </div>